Address:
  ip: '0.0.0.0'
  port: 44044
Background: 'image2.jpg'
Auth: false
User:
  username: 'admin'
  password: '1963a5d83887dc5eef7947510655c6e4ac7d22c0e0ecdd35d0740c24e0a3b7dc'
TLS:
  crt: certificates/local.crt
  key: certificates/local.key
Sessionkey: 'PXxv254dL3MuKtOxQuJbV1hToiXDkxH8lPHrK5pi31pVhEkaO1KksamcyCHsN9XO'
Proxmox:
  up: true
  ip: 'home-ve.lan'
  port: 8006
  username: 'root'
  password: 'root'
Docker:
  up: true
  url: 'http://omv.lan:9400/api/v1/containers'
  key: '99013Vault99013'