address:
  ip: '0.0.0.0'
  port: '443'
user:
  username: 'admin'
  password: '99013'
tls:
  crt: local.crt
  key: local.key
sessionkey: 'PXxv254dL3MuKtOxQuJbV1hToiXDkxH8lPHrK5pi31pVhEkaO1KksamcyCHsN9XO'