Address:
  ip: '0.0.0.0'
  port: 443
Background: 'image.jpg'
User:
  username: 'admin'
  password: '99013Vault99013'
TLS:
  crt: certificates/local.crt
  key: certificates/local.key
Sessionkey: 'PXxv254dL3MuKtOxQuJbV1hToiXDkxH8lPHrK5pi31pVhEkaO1KksamcyCHsN9XO'
Proxmox:
  up: true
  ip: 'home-ve.lan'
  port: 8006
  username: 'root'
  password: '99013Vault99013'
Docker:
  up: true
  url: 'http://omv.home-ve.lan:9400/api/v1/containers'
  key: '99013Vault99013'